backend:
  name: github
  repo: Studio-webkilat/tailwind-nextjs-starter-blog  
  branch: main
  base_url: https://tailwind-nextjs-starter-blog-sqx2-eight.vercel.app  
  auth_endpoint: /api/auth

media_folder: "public/static"
public_folder: "/static"

site_url: https://tailwind-nextjs-starter-blog-sqx2-eight.vercel.app 

collections:
    - name: "blog"
    label: "Artikel"
    folder: "data/blog"
    create: true
    slug: "{{slug}}"
    fields:
            - {label: "Judul", name: "title", widget: "string"}
            - {label: "Tanggal", name: "date", widget: "datetime"}
            - {label: "Ringkasan", name: "summary", widget: "text"}
            - {label: "Isi Artikel", name: "body", widget: "markdown"}
